[build]
  base = "BlackRock/Hack"
  publish = "staticfiles"
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[build.environment]
  PYTHON_VERSION = "3.8"
  DJANGO_SETTINGS_MODULE = "Hack.settings"
