[build]
  base = "/BlackRock/Hack"
  publish = ""
  command = "pip install -r requirements.txt"
# && python manage.py runserver collectstatic --noinput

[build.environment]
  PYTHON_VERSION = "3.8"
  DJANGO_SETTINGS_MODULE = "Hack.settings"
